<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * The imported wiki corpus: pages + their link graph, glossary, semantic marks,
 * and SPARK unlocks. All of this is a read-only mirror of the canonical markdown,
 * regenerated by `php artisan wiki:import`.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('pages', function (Blueprint $table) {
            $table->id();
            $table->string('slug')->unique();
            $table->string('title');
            $table->string('rel_path');

            // 3-axis address (nullable — ~19 pages have malformed/legacy encodings).
            $table->string('palace')->nullable()->index();
            $table->unsignedTinyInteger('level')->nullable()->index();
            $table->unsignedTinyInteger('domain_id')->nullable()->index();
            $table->unsignedSmallInteger('room')->nullable();
            $table->string('para')->nullable()->index(); // project/area/resource/archive

            $table->text('summary')->nullable();
            $table->text('sources')->nullable();
            $table->date('last_updated')->nullable();
            $table->longText('body_md');
            $table->longText('body_html')->nullable(); // rendered in the frontend slice

            // Publishing gate — everything imports PRIVATE; promote deliberately.
            $table->string('visibility')->default('private')->index();

            $table->boolean('is_meta')->default(false);   // index/log/glossary registries
            $table->boolean('axis_clean')->default(true);  // false = needs axis review
            $table->unsignedInteger('word_count')->default(0);
            $table->unsignedInteger('inbound_count')->default(0);
            $table->unsignedInteger('outbound_count')->default(0);

            $table->timestamps();

            $table->foreign('domain_id')->references('id')->on('domains')->nullOnDelete();
        });

        Schema::create('links', function (Blueprint $table) {
            $table->id();
            $table->foreignId('source_page_id')->constrained('pages')->cascadeOnDelete();
            $table->string('source_slug')->index();
            $table->string('target_slug')->index();
            $table->foreignId('target_page_id')->nullable()->constrained('pages')->nullOnDelete();
            $table->string('display_text')->nullable();
            $table->string('anchor')->nullable();
            $table->boolean('resolved')->default(false)->index(); // false = broken link
        });

        Schema::create('glossary_terms', function (Blueprint $table) {
            $table->id();
            $table->string('term')->index();
            $table->string('owner_slug')->nullable()->index();
            $table->foreignId('owner_page_id')->nullable()->constrained('pages')->nullOnDelete();
            $table->string('section')->nullable();
        });

        Schema::create('marks', function (Blueprint $table) {
            $table->id();
            $table->foreignId('page_id')->constrained('pages')->cascadeOnDelete();
            $table->string('page_slug')->index();
            $table->string('sigil')->index();      // Def, R, A, M, ...
            $table->text('text');
            $table->unsignedInteger('para_index')->nullable();
            $table->string('route')->nullable();   // NEDF/CAST/... (resolved in a later slice)
        });

        Schema::create('unlocks', function (Blueprint $table) {
            $table->id();
            $table->string('slug')->index();       // slugify(name) — loose key
            $table->text('name');
            $table->string('status')->nullable();  // candidate / confirmed
            $table->json('components')->nullable(); // component page slugs
        });

        Schema::create('page_unlocks', function (Blueprint $table) {
            $table->id();
            $table->foreignId('page_id')->nullable()->constrained('pages')->nullOnDelete();
            $table->string('page_slug')->index();
            $table->string('unlock_slug')->index();
            $table->string('status')->nullable();
            $table->string('role')->nullable();    // owner / component
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('page_unlocks');
        Schema::dropIfExists('unlocks');
        Schema::dropIfExists('marks');
        Schema::dropIfExists('glossary_terms');
        Schema::dropIfExists('links');
        Schema::dropIfExists('pages');
    }
};
